### ISSUE TITLE
WCS conversion fails

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#109]
A user reported a failure of WCS conversion on his 4-D OH maser data cube, where the 4<sup>th</sup> axis is `Stokes`. The warning message is

    WARNING: WCS conversion of parameters failed.

and no celestial coordinates are produced. The rest frequency is defined in the header, so that’s not the problem. If I’m not mistaken, then the following line no. 179 in `wcs_coordinates.py` throws an exception:

    if header['naxis'] == 4: objects = np.concatenate((objects, wcsin.wcs_pix2world(np.concatenate((xyz, np.zeros((objects.shape[0], 1))), axis=1), 0)[:,:-1]), axis=1)

Does anyone have any idea of why this fails? I should add that `kvis` correctly displays celestial coordinates, so the WCS information is presumably complete and correct.

**Comment by SoFiA-Admin** [comment]
Some additional info: I just manually loaded the cube into Python and carried out a `wcs_pix2world()` conversion. This worked without any problem, so there is no issue with the data cube as such.

**Comment by ngiese** [comment]
To make sure, that it is really line 179, that gives the error, please comment out lines 119, 251 and 252 in wcs_coordinates.py, then run SoFiA again. The warning, that you get just tells you, that something between the lines 120 and 250 goes wrong. Could you please post the resulting error message again? It might also be helpful to see the complete output from SoFiA up to the error.

**Comment by SoFiA-Admin** [comment]
Thanks, I did as you suggested, and the resulting error messages are the following:

    Traceback (most recent call last):
      File "~/SoFiA/git/sofia_pipeline.py", line 602, in <module>
        objects, catParNames, catParFormt, catParUnits = wcs_coordinates.add_wcs_coordinates(objects,catParNames,catParFormt,catParUnits,Parameters)
      File "~/SoFiA/git/build/lib.linux-x86_64-2.7/sofia/wcs_coordinates.py", line 179, in add_wcs_coordinates
        if header['naxis'] == 4: objects = np.concatenate((objects, wcsin.wcs_pix2world(np.concatenate((xyz, np.zeros((objects.shape[0], 1))), axis=1), 0)[:,:-1]), axis=1)
      File "/usr/local/lib/python2.7/dist-packages/astropy/wcs/wcs.py", line 1347, in wcs_pix2world
        'output', *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/astropy/wcs/wcs.py", line 1249, in _array_converter
        return _return_single_array(xy, origin)
      File "/usr/local/lib/python2.7/dist-packages/astropy/wcs/wcs.py", line 1230, in _return_single_array
        "of shape (N, {0})".format(self.naxis))
    ValueError: When providing two arguments, the array must be of shape (N, 3)

Unfortunately, that leaves me with no additional clue as to what is going on, but it appears that we are calling some function with the wrong number of arguments. I wonder if this has anything to do with a mismatch between the dimensionality of the cube (originally 4, reduced to 3 by SoFiA) and that of the WCS object (presumably 4)?

**Comment by ngiese** [comment]
I think, I found out, what is the problem. In line 179 (now 180) in wcs_coordinates.py, a 4th (Stokes) coordinate was (and still is) added to the 3D pixel coordinates (RA,Dec,v) of the objects array by doing the following:

    np.concatenate((xyz, np.zeros((objects.shape[0], 1))), axis=1)

This is OK, because we have a 4D cube. In the original line 164, however, we did not make a difference between cubes that have 3 and 4 axes:

    wcsin = wcs.WCS(header, naxis=[wcs.WCSSUB_CELESTIAL, wcs.WCSSUB_SPECTRAL])

The problem here was, that we explicitly said, that the cube had sky and spectral coordinates. However, we forgot to tell Astropy that there was a Stokes coordinate for some cubes, so the 4th axis was just ignored in the wcs object. From the wcs object Astropy assumed, that we had a 3D cube. So it could not handle the 4th dimension.

I have added a check for the 4d cubes and added the stokes dimension for those. Please test.

**Comment by SoFiA-Admin** [comment]
Thanks a lot for identifying and fixing the problem. The latest fix solves the problem on my machine, and WCS coordinates are now measured and added to the catalogue. The only potential problem I see is that we now make the explicit assumption that the fourth axis is ‘Stokes’. If it were something else, e.g. time, SoFiA would presumably fail again. Is there a way to include an arbitrary fourth axis in the WCS conversion? Given that we discard the 4th axis anyway, we don’t really care what its physical meaning is. On the other hand, most 4-D data cubes will presumably use Stokes as the fourth axis, so maybe we should leave things as they are and simply accept that there are certain limitations in processing 4-D cubes...

**Comment by paoloserra** [comment]
I've gone through the changes made to the https://github.com/SoFiA-Admin/SoFiA/blob/master/sofia/wcs_coordinates.py module since Sep 2016. I wonder whether the sequence of changes and fixes has resulted in an unnecessarily complicated code.

Currently we do the following:

# if naxis!=4:
We extract celestial+spectral coordinate axes with astropy.wcs. We convert xyz into RA,Dec,Z, where Z is whatever the spectral axis is. We append Ra,Dec,Z to the objects array, and modify catParNames, catParFormt and catParUnits accordingly.

# if naxis==4:
We extract celestial+spectral+stokes coordinate axes with astropy.wcs (which, as noted by @SoFiA-Admin , will cause problems if the 4th axis is not Stokes). We add a 0 to xyz, such that each object has a valid and 0-valued coordinate along the 4th axis just extracted with astropy.wcs. We convert xyz0 into RA,Dec,Z,Stokes, where Z is whatever the spectral axis is. We discard the resulting, trivial Stokes coordinate. We append Ra,Dec,Z to the objects array, and modify catParNames, catParFormt and catParUnits accordingly.

It seems to me that if we always read celestial+spectral coordinate axes only we could simplify the code with no loss of information.

This is probably the idea behind https://github.com/SoFiA-Admin/SoFiA/commit/949e173a2675173525f31314021703eb5b65112e , which indeed limits the extracted axes to celestial+spectral only. Later, this was modified by https://github.com/SoFiA-Admin/SoFiA/commit/33a04da0f95fa2c3ed4f329e824b8d7c8d5df1c0 to fix the inconsistency between having extracted 3 coordinate axes only and adding a 4th 0-valued coordinate to xyz. Howver, considering that we do not do anything scientifically useful with the trivial Stokes coordinate, would it not be better to remove the addition of the 0-valued 4th coordinate to xyz in the first place?

I propose to make this simple change, which I have already tested on my machine with good results.

Let me know what you think.

**Comment by SoFiA-Admin** [comment]
I fully agree that the code is way too complex and therefore difficult to understand and maintain. SoFiA currently breaks the basic rule that code should never ever be duplicated, so cleaning up this module would be highly desirable. We just need to make sure that we don’t discard any information about the fourth axis that we would later need to create the 4-D output mask cube.

**Comment by paoloserra** [comment]
Proposed changes made in https://github.com/SoFiA-Admin/SoFiA/commit/3917d3c85e33a2a2bee296b49d391ce549869618
