### ISSUE TITLE
Problem with merging detections

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#112]
When running the S+C finder on the SoFiA test data cube (using a 3σ threshold, a merging radius of 1, and a reliability threshold of 95%), I end up getting **isolated pixels** or small groups of pixels that are marked as belonging to a source, although they are **not connected in phase space** with that source. An example channel map from the output mask is shown below, where an isolated pixel in the lower-left quadrant of the map is assigned to source 2 (the large galaxy near the centre), even though it is separated by tens of pixels/channels from the nearest contiguous emission belonging to source 2.

![image](https://cloud.githubusercontent.com/assets/6572706/22277149/360d5a18-e2b1-11e6-9c1a-0e88fae3bc03.png)

Similar cases also occur near source 1 at the bottom of the image (not visible here). In all of these cases, the isolated emission appears to pop up in channels that also have regular emission (but at a different location) from the respective galaxy. Some of the isolated emission is negative, some positive, so there doesn’t appear to be a pattern in terms of the the sign of the flux value.

My initial suspicion is that something’s going wrong at the merging step, but please check whether the problem occurs on your SoFiA installation as well. The parameter file I have used is attached below:
[example_parameter_file.txt](https://github.com/SoFiA-Admin/SoFiA/files/728611/example_parameter_file.txt)

**Comment by paoloserra** [comment]
I see the same behaviour.

I've also found that if I set:
merge.radiusX = merge.radiusY = merge.radiusZ = 0
merge.minSizeX = merge.minSizeY = merge.minSizeZ = 1

then that single voxel in your screenshot is not merged with the large object. In this case, since that voxel has negative value in the cube, it gets removed from the final mask (by default we only keep positive objects).

However, with the above settings there is another strange behaviour. I find that large objects are still created (i.e., adjacent voxels are still merged with one another despite having set the merging radius to zero). I had expected that merge.radius = 0 would make an separate object out of each detected voxel. Maybe somebody can double-check this too?

**Comment by SoFiA-Admin** [comment]
Thanks for checking on your machine. I also remember that setting the merging radius to 0 did record each detected pixel as a separate source, as one would expect. This suggests that some change may have occurred over the past year or so that resulted in the linker not functioning correctly any more.

**Comment by SoFiA-Admin** [comment]
This problem has been identified and fixed by @RussellJurek (see b878312b16d66c93bcb487b5fa51f4d6c965d7f1 and 696534f9698e695bc9f824c133e4b351c65a3932), and the issue can now be closed.
