### ISSUE TITLE
Automated detection/removal of artefacts

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#131]
Following our discussion during the telecon of January 8, 2018, we should investigate the possibility of offering basic algorithms for the automated **detection and removal of artefacts** in the data. Things that immediately come to mind include:

* Automated **RFI** detection and flagging
* Automated flagging of regions of **excessive noise**
* Robust **polynomial fitting** to remove residual continuum emission

Please feel free to add to that list.

Such features could be offered as additional pre-processing filters prior to source finding. The only issue to bear in mind is that parametrisation might preferably occur on the filtered cube in this case, as artefacts such as RFI and continuum emission would potentially create systematic parametrisation errors. This would require a redesign of the pipeline, as currently the cube is reloaded before parametrisation whenever input filters are applied.

**Comment by SoFiA-Admin** [comment]
The new continuum artefact flagging module is now available in the input filtering tab of the GUI for further testing. It can be activated by setting `steps.doFilterArtefacts = true`. The threshold and dilation kernel size can be controlled with `filterArtefacts.threshold` and `filterArtefacts.dilation`, with default values of `2.5` and `3`, respectively.

**Comment by paoloserra** [comment]
https://github.com/SoFiA-Admin/SoFiA/commit/ac711a71e5c4200b2567774f71198c00cdf281cf changes the default of filterArtefacts.threshold to 4 (more conservative and generally OK based on experience) and swaps the order of 2D-1D and filterArtefacts in sofia_pipeline as discussed.

**Comment by paoloserra** [comment]
@SoFiA-Admin we've gone a long way already in improving the robustness of SoFiA to artefacts. We are able to flag LOS's affected by poor continuum subtraction, and we are able to reject sources based on excessive size (X,Y,Z,Nvox,Nlos).

In my opinion this general issue can be closed as we are unlikely to implement additional methods such as polynomial fitting any time soon.

The only additional method we could consider offering within SoFiA is something equivalent to filterArtefacts but applied per channel rather than per LOS. That would be fairly easy to implement. If that is of interest I suggest to open a separate issue on that method specifically.

**Comment by SoFiA-Admin** [comment]
> The only additional method we could consider offering within SoFiA is something equivalent to filterArtefacts but applied per channel rather than per LOS. That would be fairly easy to implement. If that is of interest I suggest to open a separate issue on that method specifically.

I agree, and SoFIA 2 has this mode already built into the auto-flagger. The user can basically choose whether to apply the flagger per frequency channel, per spatial pixel, or both. This could be done in SoFiA 1 as well through a simple extension of the existing auto-flagging module.
