### ISSUE TITLE
Generally high memory usage

### ISSUE THREAD

**Issue by sam6321** [SoFiA-Admin/SoFiA#132]
I've been having some fairly significant memory allocation issues while running SoFiA in a VM.
These maybe be related to [this issue](https://github.com/SoFiA-Admin/SoFiA/issues/74), although that issue hasn't been updated in about 2 years.

I've found that I need to allocate at least 3072MB of memory to my VM instances in order to process a 100MB input file without hitting memory allocation errors.

This seems excessive considering the size of the input file, and the fact that 10MB input files seem to function fine with only 256MB of memory.

**Comment by SoFiA-Admin** [comment]
SoFiA requires about 4 times the size of the input data cube in memory for standard source finding runs. Additional memory may be required for specialised tasks, such as loading and applying a weights cube. As you pointed out, the 2D-1D wavelet filter currently requires about 40 times the size of the cube in memory, which limits its applicability to small data cubes. Was the 2D-1D filter enabled in your specific case?

**Comment by sam6321** [comment]
I was running the VM through several different parameter sets, some had the 2D-1D filter enabled and some didn't. 
I was getting memory allocation errors each time using a 2048MB memory limit, which was solved by upping the limit to 3072MB.

Here are the steps I had enabled in one of the parameter files that generated a bad_alloc:
```
# SoFiA Config for sourcefinder: supercube_run_74_sofia.par
steps.doSubcube = false
steps.doFlag = false
steps.doSmooth = false
steps.doScaleNoise = false
steps.doSCfind = true
steps.doThreshold = false
steps.doWavelet = false
steps.doCNHI = false
steps.doMerge = true
steps.doReliability = true
steps.doParameterise = true
steps.doWriteFilteredCube = false
steps.doWriteMask = false
steps.doWriteCat = true
steps.doMom0 = false
steps.doMom1 = false
steps.doCubelets = false
steps.doDebug = false
steps.doOptical = false
...
```

The error was generated during parameterisation of sources, as indicated by the stdout log:
```
...
--- 42.596 seconds since start
--- SoFiA 1.2.0-beta: Parameterising sources
Mask dilation of source 1 by 0 pix and 1 chan
Mask dilation of source 2 by 8 pix and 1 chan
Mask dilation of source 3 by 4 pix and 1 chan
Mask dilation of source 4 by 0 pix and 1 chan
Mask dilation of source 5 by 4 pix and 1 chan
Mask dilation of source 6 by 4 pix and 1 chan
Parametrisation of source 1
(Log ends)
```

And the stderr log indicates the memory allocation error occurred in the C++ code:
```
WARNING: Object 1 has possible overlapping objects within 10 pix, 1 chan.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by SoFiA-Admin** [comment]
Thank you for providing the parameter settings and log file entries. You are not using the wavelet filter, so issue #74 is not the cause of the problem. Instead, the memory error appears to occur during parametrisation. I will have a look at what could have resulted in the large memory usage.

One suspicion I have is that the sources could be very large and fill most of the data cube, in which case the parametrisation would indeed require a lot of memory, as it needs to create several copies of the data for each source. Normally, this would not be much, as sources are usually small compared to the overall cube size. However, if a source covers a significant fraction of the entire cube, e.g. due to the presence of artefacts or a low source finding threshold, then the memory usage could become significant.

**Comment by SoFiA-Admin** [comment]
Following up on my previous comment, I modified the parametrisation module to read the source flux values directly from the data cube in memory whenever they are needed rather than reading the data only once into a separate array (see f94c035d7f8be820ec35d22d309470bb07c0c8dd). This has the advantage of not requiring any additional memory, but at the cost of potentially being slower, as the data for each source will need to be identified and extracted from the data cube array multiple times.

Note that the issue of large memory requirement would only have occurred when a source extended across a substantial fraction of the entire data cube. This situation is usually indicative of inappropriate parameter settings in SoFiA. The results returned by SoFiA are unlikely to be meaningful in this case and should be dismissed.

I will close this issue for now under the assumption that the problem has been resolved by the changes to the parametrisation module. Please feel free to re-open the issue if you still encounter problems with memory usage related to parametrisation.
