### ISSUE TITLE
New local and global noise measurement algorithms

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#134]
Users running SoFiA on continuum images have expressed their desire to have a local noise measurement algorithm implemented in SoFiA that would allow regions of enhanced noise, e.g. around bright continuum sources, to be scaled accordingly. Note that the current noise scaling algorithm in SoFiA will only measure the noise along an entire axis of the cube, so this would be an enhancement of the current noise scaling module. We should discuss whether a simple RMS measurement should be used, or whether more sophisticated, robust noise measurement algorithms should be offered.

**Comment by SoFiA-Admin** [comment]
Local noise measurement has now been implemented, although the current implementation is still crude and would benefit from improvements. Several new parameters have been introduced to control this new feature. `scaleNoise.method` selects whether `global` (default and previous behaviour) or `local` noise measurement should occur. Local noise measurement is done on a discrete grid the size of which is set by `scaleNoise.gridSpatial` and `scaleNoise.gridSpectral`. The measurement happens across a window of size `scaleNoise.windowSpatial` and `scaleNoise.windowSpectral`, which can therefore differ from the grid size. At the moment, an entire grid cell is filled with the noise value measured across the window centred on that grid cell, but this could be improved, e.g. by allowing linear interpolation between grid points.

**Comment by paoloserra** [comment]
Do I understand correctly that the actual window and grid size are equal to the input values + 1 ?

**Comment by paoloserra** [comment]
See attached image that shows how well this does on a continuum image. (This was a simple 6 sigma cut using an std noise measurement on negative pixels only).

![compare_global_local](https://user-images.githubusercontent.com/6591265/37145609-92cca8d4-22c1-11e8-823b-cba89b5b6782.gif)

**Comment by SoFiA-Admin** [comment]
That looks impressive, and far better than what I would have expected! I also tried the new algorithm on the SoFiA test data cube, and for some reason it performs much worse, with lots and lots of false detections popping up that hadn’t been there before.

Regarding the window and grid size, this will only be increased by 1 if the user-specified values are odd, but not when they are already even to begin with. This is to ensure that the half-width is an integer number.

**Comment by SoFiA-Admin** [comment]
Continuing from where I got interrupted last night: In the process of implementing the new noise measurement, I also significantly improved the `GetRMS()` function that measures the noise level. It is now possible to measure the noise only on negative pixels, only on positive pixels, or on all pixels (as was the case before). This works for the `mad` and `std` methods, but (not) yet for Gaussian fitting which will only use negative pixels by default at the moment.

I implemented three additional parameter settings, `scaleNoise.fluxRange`, `SCfind.fluxRange` and `threshold.fluxRange`, that allow this new setting to be applied by the noise scaling, S+C finder and threshold finder algorithms, respectively. The allowed values are `negative`, `positive` and `all` (the default and previous behaviour). It would be desirable to expand this mechanism to the Gaussian fitting as well, which currently ignores the `fluxRange` setting and is hard-coded to use only negative pixels.

The improvement to SoFiA in general is phenomenal. By changing the S+C finder algorithm from the standard Gaussian fitting to standard deviation on negative pixels, the SoFiA run on the test data cube speeds up by a significant factor without any noticeable change in the results. The source finding now happens within the blink of an eye, so SoFiA has become an awful lot faster by simply switching to a different, but equally robust, noise measurement algorithm. We should consider changing the default settings of the affected modules as well. This can be discussed at our next meeting.

**Comment by paoloserra** [comment]
Given your comment on speed I think it is appropriate to implement a two-pass strategy for the std rms measurement. I've done that with https://github.com/SoFiA-Admin/SoFiA/commit/62991b0018952dce9bf0934712a68cdf2f05001f

**Comment by paoloserra** [comment]
> Regarding the window and grid size, this will only be increased by 1 if the user-specified values are odd, but not when they are already even to begin with. This is to ensure that the half-width is an integer number. Note that this behaviour and requirement might still change as I improve the currently somewhat crude implementation of the algorithm, so this may not be final yet.

The reason I find this confusing is that for a window to be exactly centred on the pixel of interest the window must have an odd size. In this case, a window of size 1 is the same as no window, and a window of size 3 includes 9 pixels centred on the pixel of interest. My suggestion would be to constrain the window size to be an odd number.

The term "grid size" is also a little confusing. I think it might be better to call it grid spacing. Something like "running window step" might be even more intuitive. I don't see why this number should be even. Setting the grid spacing to 1 means that the window is moved by one pixel at each step.

Finally, the grid spacing should never be larger than the window spacing, else there will be pixels with no noise measurement.

**Comment by SoFiA-Admin** [comment]
Note that things are not as simple as that. You cannot have arbitrary grid and window sizes, as windows need to be centred on grids, so they must either both be odd or both be even. In principle we could support both possibilities, but that would add a more complicated rule for users to ensure that they don’t make one odd and the other even. Requiring both to be either odd or even is simpler from a usage point of view.

There are two reasons for why I chose even sizes in the end. One is that most data cubes are of even dimensions. Hence, an even-sized grid can be exactly centred within the cube volume, with same-sized edges on all sides. You cannot centre an odd-sized grid on an even-sized cube. The other reason is that I need to take the radius of the grid and window sizes, which need to be integer numbers, requiring even-sized window and grid widths.

I suggest that we discuss all of this at our next telecon.

**Comment by paoloserra** [comment]
> By changing the S+C finder algorithm from the standard Gaussian fitting to standard deviation on negative pixels, the SoFiA run on the test data cube speeds up by a significant factor without any noticeable change in the results. The source finding now happens within the blink of an eye, so SoFiA has become an awful lot faster by simply switching to a different, but equally robust, noise measurement algorithm. We should consider changing the default settings of the affected modules as well. This can be discussed at our next meeting.

Just a comment that the dramatic improvement in speed reported for the test cube should not be expected for larger cubes. I've tested the different noise measurement algorithms on a (512,512,700) cube (about 700MB) and the execution time of S+C does not vary significantly. I think the reason is that for large cubes most of the S+C execution time is spent convolving the cube with the various smoothing kernels.

**Comment by ngiese** [comment]
Yesterday, I talked to @vdhulst, who suggested, that when estimating the noise with the std method using the negative pixels only, it might be better calculating it as
![latex_b6872ec53e7b030237d9e2a2cf6122ba](https://user-images.githubusercontent.com/6600031/37346922-f2ce2bbe-26d0-11e8-8c13-912433350d75.png)
instead of using the numpy.std() function.
We can set the mean to zero, because we assume that anyways when mirroring half of the negative values. I wrote a small script to see, what the difference in execution time is depending on the size of the cube:
https://github.com/ngiese/testing/blob/master/SoFiA_std_execution_time.py
The resulting plot suggests, that @vdhulst is right, because the mirror+numpy.std method takes approximately twice as long as when we calculate it on our own.
![comparison](https://user-images.githubusercontent.com/6600031/37347189-884b4b90-26d1-11e8-8239-3adcf7672965.png)

**Comment by RussellJurek** [comment]
Do we know what the numpy.std() method is doing? I'm assuming they're doing
it the fast way and keeping a running tally of sum(x) and sum(x^2). That
would explain a factor of 2 in execution time. When you assume mean(x) is
0, you don't have to calculate sum(x).

**Comment by ngiese** [comment]
I had a look at the numpy git repository and found the following:
https://github.com/numpy/numpy/blob/master/numpy/core/_methods.py#L133
and
https://github.com/numpy/numpy/blob/master/numpy/core/_methods.py#L86
The standard deviation is calculated as the square root of the variance. The variance is calculated in two steps: first the mean is calculated and in a subsequent step the standard deviation. These steps cannot be combined into one (not sure though, what you mean by 'running tally'). Assuming the mean is zero, I saved time by 1) not calculating it and 2) not having to subtract it from the array elements before squaring the array. This is probably the reason, why I save more than half of the time needed for numpy.std().

**Comment by RussellJurek** [comment]
If you expand the formula for standard deviation, you get std_dev(x) =
sqrt(   mean(x^2)   -    [mean(x)]^2   ). The mean of both is just a
constant scaling in this case, the number of kernel elements. That means
you keep a running tally of x and x^2 as you slide the kernel along. For a
box of side length L, that means you subtract the L elements from the old
trailing edge and add the L new elements from the new leading edge. This is
the standard method of implementing a sliding box mean. It applies equally
well to the standard deviation. Except now you have to also keep a tally of
x^2. This method applies to all linear metrics/statistics that you want to
use with a sliding box. This algorithm is the smoothing equivalent of FFT.
That's why most commercial imaging tools don't implement many non-linear
smoothing algorithms.

The cost of this tallying approach is  2 x L subtraction + 2 x L additions +
1 subtraction + 1 sqrt. It scales as O(L). You have to do twice as many
subtractions and additions for the standard deviation as you do the mean.
That's because you need two tallies. This would give you a factor  of 2 in
speed when setting the mean to 0. If you aren't doing it with tallies, but
directly calculating the standard deviation of L^2 elements each time, then
the cost is L^2 additions + 1 division + L^2 subtractions + L^2 additions +
1 division + 1 sqrt. Some people are tempted to divide by L^2 as they add
the values. Unless you've got a special CPU with combined `multiply plus
add' functionality this is still two operations. It's fewer operations to
add them all together and then divide once at the end. It scales as O(L^2).
In this case, setting the mean to zero avoids having to do the L^2
additions + 1 division + L^2 subtractions. That's a substantial saving of
about 2/3rds. If the divide by L^2 is included in the additions and
subtractions that's potentially a lot of unnecessary work.

The problem with the direct method is that it scales as O(L^2). If you want
to do a 10x10 element box it'll take 10 times longer than the tally method.
The difference in O(L) vs O(L^2) means that you can get the standard
deviation for every point along one of the axes in the same amount of time.
The tally method is only possible however when you want to do a sliding
box/running average. It isn't appropriate for a coarse grid like we're
using. We *could* switch to the tally method along a coarse set of grid
lines. Instead of doing the full method at each point of a coarse grid.
Then we'd only have to interpolate along 1 axis. The user could be given
the option to decide which axis we interpolate and how coarse the grid
lines are.

It might also be useful for 3D datacubes in this form. We'd slide along
z/frequency and use a grid in ra and dec. Note that this will probably
incur a lot of cache thrashing. Datacubes are usually organised x,y,z in
memory, which makes sliding along x the fastest way to do it. You need to
re-organise the datacubes to z,x,y or z,y,x if you want it to be as fast as
possible. Alternatively, you slide along ra and use a grid in dec and
frequency.

**Comment by ngiese** [comment]
OK, got it. If I understood the code correctly, that's not what numpy.std does. As long as we use python, we should make use of the the optimizations that come with the ndarray class. The approach, that you suggest, would only make sense if we switch to a lower level programming language (e.g. C).

**Comment by SoFiA-Admin** [comment]
@paoloserra

> Just a comment that the dramatic improvement in speed reported for the test cube should not be expected for larger cubes. I've tested the different noise measurement algorithms on a (512,512,700) cube (about 700MB) and the execution time of S+C does not vary significantly. I think the reason is that for large cubes most of the S+C execution time is spent convolving the cube with the various smoothing kernels.

That’s an interesting result. I haven’t started testing yet how the different algorithms scale with cube size, but your result suggests that they probably won’t scale linearly. Given that the noise measurement algorithms could be improved without much effort, we may want to generally consider revisiting our algorithms and looking for ways to optimise them with respect to speed. I would’t be surprised if quite a few of our modules could be made much faster with just a few small changes.

**Comment by SoFiA-Admin** [comment]
@ngiese

> Yesterday, I talked to @vdhulst, who suggested, that when estimating the noise with the std method using the negative pixels only, it might be better calculating it as
(∑(<var>x</var> − <var>µ</var>)<sup>2</sup> / <var>N</var>)<sup>1/2</sup>
instead of using the numpy.std() function.
We can set the mean to zero, because we assume that anyways when mirroring half of the negative values. I wrote a small script to see, what the difference in execution time is depending on the size of the cube:
https://github.com/ngiese/testing/blob/master/SoFiA_std_execution_time.py
The resulting plot suggests, that @vdhulst is right, because the mirror+numpy.std method takes approximately twice as long as when we calculate it on our own.

Thanks a lot for these useful suggestions. In fact, I already implemented this earlier this week for exactly the reasons you mentioned: getting rid of the need to flip signs and removing the calculation of the mean which we can set to zero. While I haven’t compared the speeds yet, the new STD algorithm does not appear to be noticeably slower or faster than the old one when running it on the test data cube, although @ngiese’s test would suggest that we actually gain a factor of 2 in speed overall, which is an excellent result.

In the same way I also revised the definition of the median absolute deviation. We currently calculate:

MAD = median(|<var>x</var> − median(<var>x</var>)|)

which is the median absolute deviation about the median. The purpose of the inner median is to get a robust estimate of the mean. However, since we assume Gaussian noise with a mean of zero, the median must also be zero by definition, so we can actually entirely skip one of the median calculations and instead determine the median absolute deviation about zero:

MAD₀ = median(|<var>x</var>|)

which is substantially simpler and faster. I implemented and tested it on the test data cube. As expected, this speeds up the algorithm significantly, and the new MAD₀ is as robust as before, but almost as fast as the STD now! I also tried to figure out how SciPy calculates the median, but was unsuccessful. The reason for why we may want to check is that the median calculation can be made even faster with a few tricks, e.g. by not sorting the entire array, but only the upper or lower half, which is enough to extract the median value.

As @ngiese already indicated in response to @RussellJurek’s comments, the problem with Python is that we will need to make use of whatever C-based algorithms are built into packages like NumPy or SciPy, as we can’t implement any algorithms in Python from scratch for reasons of speed. If SoFiA was written in C/C++, this limitation wouldn’t exist and we could simply write our own optimised algorithms that would meet our specific needs.

**Comment by paoloserra** [comment]
> I haven’t started testing yet how the different algorithms scale with cube size, but your result suggests that they probably won’t scale linearly.

With one caveat: S+C limits the noise calculation to 1M pixels. For cubes larger than 1M pixels the noise calculation should always take the same time, while the convolution time grows with cube size. Note that 1M pixels is 0.5% of the (512,512,700) cube I used for my test.

**Comment by ngiese** [comment]
@SoFiA-Admin - on how the nanmedian is calculated:

The scipy.stats.nanmedian function that we use in sofia/functions.py is deprecated. That's the reason for having the version check before importing the nanmedian, because nanmedian was added to numpy in version 1.9 and we require numpy version >=1.8.
(https://github.com/SoFiA-Admin/SoFiA/blob/master/sofia/functions.py#L10)
All other nan* functions were already added in numpy version 1.8.
If we look for documentation, we should therefore concentrate on the numpy versions of these functions.

The numpy.nanmedian function does not require all array elements to be sorted. It basically reshapes the array to 1D, removes all NaNs and then finds the element that would be in the center of the array if the array was sorted. The last step is happening here:
https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L3315
(if the array has an even number of elements, you get the mean of the central two elements)

The median method is based on numpy.partition, which uses the Introselect algorithm. There's a Wikipedia article about it:
https://en.wikipedia.org/wiki/Introselect

**Comment by SoFiA-Admin** [comment]
Thanks, @ngiese, for the information. It looks like NumPy’s `nanmedian` has been nicely optimised already, so we should stick to that version then.

**Comment by paoloserra** [comment]
A few comments on the local noise measurement as of https://github.com/SoFiA-Admin/SoFiA/commit/9688193bea223bac4ede4dd50e582006bd6980cb#diff-28432971492a3233a340423c3365d196 .

We currently offer two methods: "global" and "local". I'm generally in favour of self-explanatory names, such that users understand immediately what the method does. For this reason I would propose to rename "global" to something like "along_axis" or "axis" or "1D". Similarly, we could rename "local" to "window" or "tile" or "2D/3D". (Not great names, but at least they say what the methods do. I'd be more than happy if somebody could come up with better ideas.) 

The "local" method was motivated by using SoFiA on continuum images. If only for this reason, I suggest to remove the lower limit of 4 on the spectral size of the window. The lower limit should be 1.

The current method assigns the noise measured over a window of size W=2N to a tile of size T=N. If I understood correctly this was motivated with Nyquist sampling but I'm not sure Nyquist sampling applies to this at all. More generally, I'm in favour of not taking such decisions for the user. I would prefer to either always set W=T, or to let the user decide what W and what T s/he wants. In the latter case I would request users to provide the size of the tile (i.e., the resolution of the noise measurement), and a factor > 1 to set the size of the window over which the noise is actually measured for any given tile.

I'd prefer to not constrain W and/or T to be even or odd number. They can be whatever. We just need to be careful in case the number of tiles of chosen size that can be fit in a cube is not integer.

**Comment by SoFiA-Admin** [comment]
@paoloserra: We discussed your suggestions at this week’s meeting. Here’s a summary of our conclusions:

* Regarding the method names, there was general agreement that the current names are not optimal, in particular for `global`. Unfortunately, we failed to figure out names that would be simple and concise at the same time, so we’ll have to do some more brainstorming.
* The suggestions regarding window/tile sizes and odd vs. even are all fine and will be implemented accordingly.
* Regarding the tile size, we agreed that it would be useful to allow the user to set this manually, but we also noted that there is generally no benefit in picking a tile size that is substantially smaller than the window size. Therefore, the decision was made to implement the tile size as a hidden option (not available through the GUI) and chose a default of half the window size if not set by the user. This will give power users the ability to modify the tile size while inexperienced users will be provided with a sensible default value.

**Comment by SoFiA-Admin** [comment]
Thanks everyone for contributing to the discussion on this topic! Local noise measurement is now finalised and (hopefully) fully functional. To summarise the main points:

* Users can now chose between `scaleNoise.method = global` and `local` for global (i.e. across an entire 2-D plane of the cube) or local (i.e. in a running 3-D window) noise scaling.
* For local noise scaling, spatial and spectral window sizes can be set with `windowSpatial` and `windowSpectral`, respectively. These need to be odd integers (as discussed at our last meeting) of 1 or greater (note that a choice of 1 wouldn’t make much sense unless the data cube is a 2-D image).
* To speed up the process, local noise measurement happens on a grid the size of which is controlled by the `scaleNoise.gridSpatial` and `scaleNoise.gridSpectral` parameters which again have to be odd integers of 1 or greater. If set to 0 instead, SoFiA will automatically set them to about half the corresponding window size (±1 pixel). Grid sizes are a hidden parameter not available in the GUI.
* Lastly, a parameter `scaleNoise.interpolation` was introduced to tell SoFiA whether to interpolate noise values in between grid points. Possible choices are: `none` = fill the entire grid cell with the corresponding noise value; `linear` = do a linear interpolation of noise values in between grid points; `cubic` = do a cubic spline interpolation of noise values in between grid points. Cubic spline interpolation gives the smoothest noise maps, but is also the slowest of the three options.
* An additional parameter, `steps.doWriteNoiseCube`, was introduced to allow users to write the noise cube measured by SoFiA to disk for later inspection. The name of the file will be `<basename>_noise.fits`.
* As mentioned before, the entire noise measurement module of SoFiA was updated and optimised in this process, offering much faster `std`, `mad` and `gauss` algorithms (`scaleNoise.statistic`) that can be applied to negative, positive or all pixels (`scaleNoise.fluxRange`).

All of the changes have been uploaded to GitHub. Please test and let me know if anything isn’t working as expected. Once everyone is happy, this issue can be closed.

**Comment by SoFiA-Admin** [comment]
This issue can now be closed, as everything appears to be working fine. Please feel free to open a new issue if any problems are encountered with the local or global noise scaling.
