### ISSUE TITLE
Output products for 2D input files missing or incorrect

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#156]
Output products are generally assumed to be three-dimensional. This causes a few problems for 2D input images:

- WCS conversion of detected sources fails because they are calculated assuming a 3D cube while the header only has information about the first two axes.
- The output catalogue returns values for a third dimension (e.g. centers and bounding boxes) that is not actually present in the input data

**Comment by paoloserra** [comment]
> * WCS conversion of detected sources fails because they are calculated assuming a 3D cube while the header only has information about the first two axes.

fixed by https://github.com/SoFiA-Admin/SoFiA/commit/6da3f63ffa0f35fec14ad119060c1d8037e3aaa5

> 
> * The output catalogue returns values for a third dimension (e.g. centers and bounding boxes) that is not actually present in the input data

I would argue that this is neither a bug nor a major issue. Presumably users who run SoFiA on a 2D image know that catalogue parameters having to do with the third axis (e.g., line width) are not relevant for them. Those parameters seem to have clearly useless values anyway (e.g., line widths are = 0). So I'm going to close this issue. Please open a separate issue requesting the removal of those parameters as an enhancement if necessary.
