### ISSUE TITLE
Parameter names

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#17]
We plan to update parameter names following VO conventions. Current standard seems to be that described at http://www.ivoa.net/documents/REC/UCD/UCD-20050812.html and http://www.ivoa.net/documents/REC/UCD/UCDlist-20070402.html

**Comment by SoFiA-Admin** [comment]
I implemented the naming scheme + unified content descriptors (UCDs) as described above into SoFiA, and everything seems to be working fine. I made just a few changed as compared to the table above, including:

* `f_tot` was changed to `f_int` to be internally consistent with the corresponding Busy Function parameter, `bf_f_int`.

* The UCDs for `w20` and `wm50` were changed from `phys.size;spect.line` to `spect.line.width`, which seems a more appropriate choice. Note, however, that `spect.line.width` is actually defined as the FWHM of the line and not line width in general, so technically speaking the association is not correct. This appears to be a case of a very unfortunate UCD definition by the VO, as the name of the UCD itself would suggest “line width” of any kind, whereas a separate UCD, e.g. `spect.line.fwhm`, should exist to explicitly refer to the FWHM.

* `ID_old` was reintroduced as `id_old` with UCD `meta.id`. In the longer term, we may want to get rid of this item altogether, as the user will presumably only want one unique ID per source rather than two.

UCDs are written only to the XML catalogue, where the VO table definition allows for an additional `ucd='...'` attribute to the `field` element. They are not really visible as such, although Topcat has an option to display table header information that includes UCDs. Feel free to test all of this to ensure that everything is working correctly and without crashing.
