### ISSUE TITLE
Optical find does not produce catalogues when selecting Cubelets as output

### ISSUE THREAD

**Issue by apopping** [SoFiA-Admin/SoFiA#71]
When "cubelets" are selected as one of the output products while using the "Optical find" feature then SoFiA does not produce output catalogues. However it also doesn't crash, neither does it give a warning. 
Mom0 and Mom1 files are written correctly

**Comment by paoloserra** [comment]
This error is caused by the fact that when processing a subcube (whether as part of the optical finder or using the subcube selection outside the optical finder) individual source products (moment maps, cubelet, mask) are written incorrectly. The FITS files cannot be opened -- KVIS gives the error:
Insufficient data in file, need: 90 bytes, 0 remaining
foreign_guess_and_read: error reading FITS file
As a result, the pipeline is exited with exit code 1, and all following actions (including the writing of catalogues) are not performed. So this is a more general bug which is not related to the optical source finder. We will open a separate issue.
