### ISSUE TITLE
2d-1d memory usage

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#74]
2d-1d uses an excessive amount of memory.

**Comment by lfloeer** [comment]
I thought I'd shed a little light on how memory the 2D-1D algorithm really needs and what it is currently using.

To perform iterative 2D-1D de-noising the algorithm _requires_ to keep in memory:
- The original data array (float32)
- A work array of three times the original data size (float32)
- The multi-resolution support (MRS, bool)

While the MRS are only boolean values, the number of booleans required are _spatial scales_ x _spectral scales_ x _data size_. This is typically the largest contribution to the memory footprint of the algorithm. The function `denoise_2d1d` currently also keeps an additional copy of the input data cube and a boolean array to indicate invalid values in the input data cube (to set them to 0 after reconstruction). These two arrays could be optimized away, but the general memory footprint of the algorithm is still much larger than typical matched-filtering algorithms.

Other things that could be optimized are:
- Leave out the MRS. This will reduce reconstruction fidelity but I'm not sure how big the impact on source finding will be, since the actual reconstruction fidelity is not really important.
- Use the C++ Vector specialization for booleans which uses bits instead of bytes for boolean storage (a factor 8 in storage), but I'm not sure how well Cython deals with this particular instance of C++ black magic.

**Comment by RussellJurek** [comment]
I'm pretty sure that the pipeline already carries a copy of the input data
cube for masking out invalid values. In that case we could just apply that
after calling denoise_2d1d, instead of it being done internally.

I agree with Lars on converting the boolean arrays to bits.

Accessing bit values requires masking an 8-bit chunk belonging to a byte,
because bytes are the smallest, directly addressable part of memory. It's
further complicated by the fact that the C/C++ standard doesn't specify a
size for booleans. On most systems booleans are 1 byte (like a character),
but it's not uncommon for systems to use 4-byte integers as a boolean. That
means in the worst case scenario the boolean arrays are 32x larger than
they need to be. The bitset arrays in C++ were designed to handle this
situation. They're a class that handles the 8-bit masking so that you can
use individual bits to store true/false values. There is an overhead
associated with this though. Once you request a value from a bitset, it
loads the relevant byte from memory into a temporary variable (static class
variable) and then calls the shift registers 0-7 times to align the desired
bit value with the start of the byte. It then converts this shifted 8-bit
binary number to a decimal value between 0-255. If it's >= 128, then the
bit value was 1 and 0 otherwise. It's a lot of stuffing about, which is why
it's all handled inside the bitset class' member functions. Calling the
shift registers isn't a huge overhead so I wouldn't worry about it, but it
is an overhead nonetheless. As are the overheads associated with passing in
and out of the class and calling its member functions. The trick is to
structure the code so that it accesses bitsets as sequentially as possible,
so that you aren't repeating shift register calls. The other overheads are
unavoidable. You use boolean arrays to optimise for speed and bitsets to
optimise for memory. In this case the memory optimisation's speed cost is
probably negligible. I think this is the right design trade-off. I just
wanted to lay out the situation for everyone. Especially if the speed hit
turns out to be noticeable.

Bitsets are a C++ class like any other. I'm pretty sure that Cython
supports left bitshifts (it'd be weird if it didn't), so I'd be surprised
if it can't handle a bitset. It's probably worth testing out before making
changes to the 2D-1D module though.

**Comment by RussellJurek** [comment]
I forgot to point out that once the 2D-1D module exceeds the available RAM,
a users system uses a paging file on their harddrive. This is very slow.
It's possible that reducing the memory footprint (in particular by
converting from booleans to a bitset) will shrink the paging file enough to
actually speed up the 2D-1D module in this instance.

**Comment by SoFiA-Admin** [comment]
As this would require a redevelopment of the algorithm, which is beyond our currents means, I will mark this as “won’t fix” and close this issue.
