### ISSUE TITLE
Add new source parameters

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA#75]
Following a discussion with the kinematics group we have decided to add the following parameters:

- ☑ major axis, minor axis and PA of ellipse fit to 3-sigma contour of moment-0 image
- ☒ same parameters as above but deconvolved with the PSF
- ☒ deconvolved ellipticity
- ☒ number of beams along ellipse major and minor axis
- ☑ PA of the kinematical major axis
- ☑ local rms value (MAD statistics, having masked all sources in cubelet)
- ☑ integrated S/N ratio

**Comment by SoFiA-Admin** [comment]
I noticed that the rms calculation for unmasked regions in a sub-cube around a source was already done in the parameterisation module (parameter: rms). The algorithm has now been changed from standard deviation to the more robust MAD. Results then get scaled by the theoretical factor (~1.5) to estimate standard deviation levels from the MAD under the assumption that the data follow a normal distribution.

**Comment by SoFiA-Admin** [comment]
Calculation of the integrated signal-to-noise ratio has been implemented by simply dividing the measured total flux by sqrt(_N_) times the measured noise in the sub-cube around the source, where _N_ is the number of spatial and spectral pixels masked as part of the source.

To get the actual integrated SNR, this would still have to be divided by the **beam solid angle** to correct for the fact that the cube is oversampled in the image domain. However, this would have to happen in a different module, because the cube header information is not currently passed on to the parameterisation module, as we decided that all parameterisation should initially be based on the raw data, and conversion to physically meaningful parameters should happen at a later stage.

**Comment by SoFiA-Admin** [comment]
Calculation of the position angle of the kinematic major axis of sources is now implemented. This works by first calculating the centroid of the emission in the sky plane, _x_(_z_) and _y_(_z_), for each spectral channel, _z_, across the source and then fitting a straight line through the set of centroids:

_y_(_z_) = _a_ × _x_(_z_) + _b_.

The position angle is then defined as:

_PA_ = atan(_a_) − 90°.

Note that the addition of 90° ensures that _PA_ = 0° corresponds to north, as already implemented in the ellipse fitting. The resulting position angles are made to be in the range of −90° to +90°.

Two examples from the SoFiA test data cube are attached. They show the galaxy near the upper edge of the cube (galaxy 1) and the large galaxy near the centre (galaxy 2). In both cases, the centroids, _x_(_z_) and _y_(_z_), are plotted, with the black, dashed line showing the result of the fit.

In the case of galaxy 1 we get a very nice fit and a position angle of about −8°. In the case of galaxy 2 there is strong warping of the disc, leading to a mean fitted position angle of about +35°, which is close to the _PA_ of the inner disc, but significantly different from the _PA_ of the outer disc. In such warped cases the accuracy of our measured _PA_ will generally be limited, and there isn’t much we can about it.

![galaxy_1](https://cloud.githubusercontent.com/assets/6572706/14097508/5353dbd0-f561-11e5-9859-7e4a3a54d712.png)
![galaxy_2](https://cloud.githubusercontent.com/assets/6572706/14097509/59fcbefc-f561-11e5-93df-28217c015dab.png)

**Comment by bwinkel** [comment]
I think, you have to calculate the PA from world coordinates not just from pixels. AstroPy has a function to do this (it's rather simple, so you could also just copy the implementation):

http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord.position_angle

**Comment by SoFiA-Admin** [comment]
I’m not sure if that’s desirable, because the purpose of the parameter is to give the kinematics working group an initial estimate of the position angle of the kinematic major axis for their tilted-ring analysis. My suspicion is that they operate in pixel-space, as the rotation curve is measured in local galactocentric coordinates rather than in the world coordinate system of the data cube. We’ll have to check with them again, though, to be sure.

**Comment by paoloserra** [comment]
Thanks! Is this done using the geometric mean position in each channel? If not, does the algorithm uses only positive pixels?

**Comment by paoloserra** [comment]
PA's are often defined using the full 360 deg range (0 to 360 or –180 to +180) in order to include information about which side is receding. This may be useful for the kinematic pipelines too.

**Comment by SoFiA-Admin** [comment]
The algorithm calcuates the intensity-weighted centroid in each channel using all pixels brighter than 3 sigma. I then check whether there are at least two channels with valid centroids and then do a linear regression on the set of centroids. Regarding the angles, at the moment it is not possible to derive which is the receding side, because the linear regression doesn’t distinguish whether the data points run from, say, bottom-left to top-right or the other way around. However, it should be relatively straightforward to check where the first centroid is positioned relative to the last one and use that to determine the full angle. The only problem is that in the case of severe warping, as in the example above, the outcome may be wrong.

**Comment by SoFiA-Admin** [comment]
**Ellipse fitting** to the 3σ contour of the **moment-0 map** has been added. The algorithm first generates a moment-0 map, _M_₀(_x_,_y_) from the source mask and at the same time counts the number of data values, _N_(_x_,_y_) that have contributed to each pixel of the moment map. Next, the condition

_M_₀(_x_,_y_) > 3 × rms × sqrt[_N_(_x_,_y_)],

where rms is the local rms in the data cube, is checked for each pixel, (_x_,_y_), and a separate mask is set to 1 if the condition is met and 0 otherwise. Lastly, an ellipse is fitted to that mask, thereby ensuring that all pixels fulfilling the 3σ flux criterion above are assigned equal weight. The new ellipse parameters (`ell3s_maj`, `ell3s_min` and `ell3s_pa`) are again relative to the pixel grid of the data cube. Position angles are converted to degrees and run from −90° to +90°, with 0° pointing up.

**Comment by SoFiA-Admin** [comment]
After receiving feedback from the kinematics working group, a few changes and improvements have been implemented in the algorithm determining the position angle of the kinematic major axis. The following changes were made:

* Instead of linear regression I now use **Deming regression** which minimises the squared Euclidean distances rather than vertical projections. This is more appropriate in our case where _x_ and _y_ are independent parameters in a two-dimensional plane rather than dependent through the functional form _y_ = _f_(_x_). Linear regression would break down in cases where the position angle is close to 0°.

* Instead of uniform weighting of all data points, I now use the **square of the total flux** in each channel as the weight. This ensures that brighter parts of the inner disc have higher weights so that the derived PA is more closely aligned with that of the inner disc. This should give us better performance on galaxies with strongly warped outer discs.

* Finally, I now calculate the **PA in the full range** of 0° to 360°, taking into account how the approaching and receding parts of the disc are aligned. In order to achieve this, I calculate the angle of the vector pointing from the centroid in the first valid channel to that of the last valid channel. I then check if the difference between that angle and the derived kinematic PA is greater than 90°, in which case 180° are added to the kinematic PA. Note that this could still go wrong if the disc has an exceptionally strong warp that leads to a change in position angle of more than 90°. On the other hand, we can use the difference between the two angles above to identify warped discs.

Note that the kinematic PA currently does not point towards the receding side of the disc, but rather to the side that occupies the upper part of the channel range covered by the galaxy. This is due to the fact that I don’t have WCS information available in the parametrisation module. At a later stage we will have to look at the WCS to assess whether increasing channel numbers indeed correspond to increasing radial velocities. If that’s not the case (e.g. because the velocity axis is flipped or given in frequency rather than velocity), we would have to rotate the kinematic PA once more by 180°.

The two example galaxies from one of my previous posts are attached again, this time with results from the improved algorithm. Note the much better fit in both cases and the PAs now pointing towards the red end of the data set. Although the kinematic PA for the warped galaxy is still not perfectly aligned with the PA of the inner disc, the fit is significantly better than before and presumably sufficiently accurate as an initial estimate for the kinematics folks.

![galaxy_1](https://cloud.githubusercontent.com/assets/6572706/14377076/410cebfc-fd5d-11e5-90f1-37e8936e8a56.png)
![galaxy_2](https://cloud.githubusercontent.com/assets/6572706/14377077/44b3848c-fd5d-11e5-8ae1-7d7be9dcc65c.png)

**Comment by SoFiA-Admin** [comment]
All requested parameters (where possible) have now been implemented, and this issue can be closed. Note that all parameters are still provided in pixel coordinates rather than in WCS coordinates at this stage. However, this is a more general issue with a range of parameters provided by SoFiA and needs to be addressed separately in a more general way. We may want to open a separate issue on parameter conversion.
