### ISSUE TITLE
memory mapping problem when using latest astropy version

### ISSUE THREAD

**Issue by apopping** [SoFiA-Admin/SoFiA#80]
The recent astropy (version 1.0.2) has different defaults when reading the data, compared to previously.
It tries to map the data, which causes problems when using large fits files as the data should be read into RAM, rather than being mapped.

**Comment by apopping** [comment]
After upgrading my version of astropy I ran in the same problems as a SoFiA user when loading large fits files. In the task import_data I have added "memmap=False" to every occurrence where data is being read.

seems to work now

**Comment by RussellJurek** [comment]
It should be noted that memory mapping files is a useful technique for
dealing with large files. It avoids a lot of the overheads associated with
loading a file into memory. It introduces additional overheads however if
you edit the file contents repeatedly and/or loop through the entire file.
I don't think memory mapping is the right choice for SoFiA. It might be an
option for dealing with 32GB+ files however once astropy's memory mapping
has been debugged.

**Comment by paoloserra** [comment]
Memory mapping had been implemented for the reason explained in https://github.com/SoFiA-Admin/SoFiA/issues/45 . We should make sure that the changes just made do not create problems elsewhere in the code.

**Comment by ngiese** [comment]
I agree we should not break other parts of the pipeline to adjust it to bugs outside of SoFiA. It seems to be a Mac/Astropy problem. I am running Astropy version 1.0.1 on Linux and memory mapping worked fine for me before the changes were made. Now that memmap is set to False the whole cube is read into memory, even if I only select a subcube. The changes should also have broken the optical finder and it should run incredibly slow now.

The problem is definitely not related to any changes in defaults, because we have been using memmap=True for a while now in the import module and there have not been any complaints before. If the newest Astropy version does not work with Mac and memmap=True, we should mention this in the installation requirements for SoFiA and find out which of the latest astropy version works on a Mac without this issue to give recommendations. Additionally, it would be nice if whoever has a Mac and encountered this problem could let the Astropy developers know. They also have a GitHub repository, so it is easy to just open an issue: https://github.com/astropy/astropy

I reopen this issue, because I don't think the problem is fixed if the solution breaks SoFiA in other places.

**Comment by apopping** [comment]
OK, maybe this needs a bit more testing.

I did not have any problems using older versions of astropy, but I have upgraded to astropy version 1.0.2 and did have a problem with the memory mapping. Based on comments from another user, it was working fine with a 0.5Gb cube, but not with a 2Gb cube. 

A first question to non-Mac users, can you work with a ~2Gb cube using astropy 1.0.2 as this is the current version when new users are installing SoFiA

**Comment by paoloserra** [comment]
Maybe using the option do_not_scale_image_data=True in astropy.io.fits.open would be a solution? This would have no effect for FITS files trivial BSCALE=1 and BZERO=0, and we could find a way around it for other cases.
Attila, since you are able to reproduce the error with memmap=True, maybe you can also check this?

**Comment by RussellJurek** [comment]
Memory mapping isn't necessary to read in a large data cube. Long before memory was available, the cfitsio library was written such that you can load just sections of a fits HDU. I went looking for an equivalent in pyfits. It looks like the pyfits package allows this to be done using the section method. This is much slower than memory mapping, but it's a viable alternative. The key point is that memory mapping isn't a necessity to load just a subsection of a data cube. The section method can be used to solve issue 80. 


http://docs.astropy.org/en/v0.2.1/io/fits/api/images.htmlhighlight=astropy%20section#astropy.io.fits.ImageHDU.section

**Comment by ngiese** [comment]
I also came across the section method and tested it as an alternative to memory mapping. It did work and I did not have the impression that it was noticeably slower. However, I remember when I read about it, it sounded a bit old and I was afraid it might be replaced by memmap. We could give it a try and see if it solves the problem. I would be much happier with this solution than trying to implement a workaround for a possible Astropy bug.

**Comment by ngiese** [comment]
I installed Astropy version 1.0.2 (from source) on Linux Mint 17 and successfully ran the version of SoFiA with memmap=True in the input module.

**Comment by RussellJurek** [comment]
My understanding is that there is a bug in the Mac OS X system calls that pyfits relies on to achieve memory mapping. 

I wouldn't worry too much about the section method becoming obsolete. It's a fundamental capability of the fits_read function in the cfitsio library that pyfits is built upon. We will always be able to write our own version of section if required. 

Cheers,
Dr. Russell Jurek

**Comment by ngiese** [comment]
I could replace memmap option with the section method. Do we agree that we should do this?

**Comment by paoloserra** [comment]
Fine with me.

**Comment by RussellJurek** [comment]
If you look at the fits_read_pix command in the cfitsio documentation,
you'll find that it *requires* the user to specify the pixel/voxel range of
the fits HDU that is to be read from disk. This means it's in no danger of
becoming obsolete. They would have to completely re-write the cfitsio
library interfaces. The format that fits_read_pix uses is an (x,y,z) origin
and the number of values to write. I'm pretty sure this command is called
repeatedly by the cfitsio function fits_read_subset, which allows you to
specify a rectangular region to be read from disk. I suspect that the
pyfits section method is based on the fits_read_subset function.

The relevant page of the cfitsio online documentation is,
https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/node9.html .

I'm in favour of using the section method instead of memory mapping. The
memory mapping is only really a cheat anyway. It worked because when you
memory map a file on disk, your machine exploits its use of paging files in
virtual memory to represent the file as a set of pages. Paging files are
quite small, 4kB to 1MB, so you effectively only load a subset of the image
while making the entire file available. The intended purpose of memory
mapping is to either handle disk I/O for files that are larger than your
available memory (because the virtual memory manager would just start
paging the file to disk as you read it in anyway) or to achieve random
access read/write on files (eg. running a binary search retrieval on a text
file with a fixed format).

**Comment by apopping** [comment]
Not sure whether you have already done this, but yes fine with me as well. After all our search it seems that the section method is better and more robust

On 30 Apr 2015, at 3:31 am, ngiese <notifications@github.com<mailto:notifications@github.com>> wrote:


I could replace memmap option with the section method. Do we agree that we should do this?

**Comment by ngiese** [comment]
Added the section method, but kept the memmap=False option in file opening. Please test!

**Comment by apopping** [comment]
I have just tested it,first the parameter file that was causing problems and I have also tested the optical finder. Both are running fine!

**Comment by RussellJurek** [comment]
w00t! Victory for pyfits.section!
