### ISSUE TITLE
Overwriting the parameter file in the gui

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#83]
A user reported, that the GUI overwrites the previously saved parameter file without asking, when the pipeline is run again after changing parameters. This is definitely a problem, when the users only save files using the GUI and if they only want to store files after they have found the right parameters. I was wondering if we should show a warning message if a file is about to be overwritten. I do understand that this behaviour is similar to other programs like e.g. text editors. I just don't know if users expect it for the pipeline.

**Comment by SoFiA-Admin** [comment]
This behaviour is explained in the user manual and necessary because SoFiA needs the parameter file as its input. The alternative would be to always generate a temporary file and run SoFiA on that, but then we run into the problem that any settings will be lost when the GUI is closed without saving the current parameter settings. So, I don’t know which option is the better one.

**Comment by SoFiA-Admin** [comment]
I updated file handling in the GUI by introducing the concept of sessions. Whenever the pipeline is launched, the current parameter settings will be saved into a temporary session file called `SoFiA_session.par` in the current working directory (rather than the currently opened parameter file). The pipeline will then be run on the session file rather than the parameter file itself. The only way to update the actual parameter file is by clicking on `Save` or `Save As...`. The warning message regarding loss of unsaved data now pops up again when closing the GUI.

The session file will also be updated when exiting from SoFiA, meaning that the last set of parameter settings will be remembered. Whenever the GUI is restarted from within the same working directory, SoFiA will automatically recover any previous session found in that directory, so users can continue to work from where they previously stopped.

This should address the issue of automatic overwriting of parameter files and be much safer in the sense that the latest settings will now always be remembered and be made available again when the GUI is re-launched (unless the user manually deleted the session file).

**Comment by RussellJurek** [comment]
I like this a lot Tobias. It's very clean and elegant. Nice work.

**Comment by SoFiA-Admin** [comment]
Thanks, Russell. A few more improvements have been implemented. The GUI now keeps track of any changes to parameter settings and will only prompt the user if an action would actually discard unsaved changes. Pop-up notifications will no longer be generated if no changes have occurred since the last save.
