### ISSUE TITLE
Source finding fails on filtered cube

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#86]
I recently ran a few tests of the **wavelet filter** combined with the **threshold finder** on the official **SoFiA test data cube** and was unable to get any sensible results out of SoFiA. The 2D-1D filter appears to be working correctly, because a sensible filtered cube is coming out at the other end. However, the output from the source finding does not appear to make any sense whatsoever. There are three galaxies in the cube, but SoFiA only ever detects one source irrespective of what threshold I set in the threshold finder. What’s even more bizarre is the fact that SoFiA reports a peak flux of 0.0009 Jy for that source, which is lower than the detection threshold I used (0.001 Jy)!

What’s more, with a slightly higher threshold of 0.01 Jy, the merging module reports the detection of no sources:

```
Merging complete
The following sources have been detected: []
```

Nevertheless, moment maps are attempted to be written. The moment-0 map, however, is empty, and generation of the **moment-1 map crashes SoFiA** with the following error messages:

```
/usr/lib/python2.7/dist-packages/numpy/lib/nanfunctions.py:220: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
...
Traceback (most recent call last):
  File "~/SoFiA/git/sofia_pipeline.py", line 529, in <module>
    writemoment2.writeMoments(np_Cube, mask, outroot, debug, dict_Header,Parameters['writeCat']['compress'], Parameters['steps']['doMom0'], Parameters['steps']['doMom1'], Parameters['writeCat']['overwrite'])
  File "writemoment2.pyx", line 146, in writemoment2.writeMoments (src/writemoment2/writemoment2.c:4909)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 190, in __setitem__
self._update((key, value, comment))
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1531, in _update
self.append(card)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1110, in append
card = Card(*card)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 442, in __init__
self.value = value
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 566, in value
value)
ValueError: Floating point nan values are not allowed in FITS headers.
Pipeline failed with exit code 1.
```

Apparently, there are some NaN values in the FITS header which causes AstroPy to fall over.

Things become even weirder: as mentioned before, I can write out the filtered cube produced by the 2D-1D algorithm, and it all looks sensible and correct. If I then load that filtered cube into SoFiA and run the threshold finder, everything is fine! SoFiA detects all sources in this case and produces moment maps and a catalogue with correct parameterisation.

Therefore, the individual components of SoFiA seem to be working correctly, but there appears to be a problem when filtering a cube and then passing it on to the source finder and merger. Some information seems to get lost along the way, causing the nonsensical behaviour.

**Comment by ngiese** [comment]
If the moment creation fails, you should not have any source in the catalogue, because the catalogue is written after the moment maps. Are you sure you get the source catalogue from the run that fails and not from an earlier run?

I output some results from after the merging and for the filtering+thresholding run the merging module produces flux values for the sources which are 0.0 for 5 of the 6 detected sources. The 6th source has a negative total flux. All are discarded in the part of the code that removes negative sources. This part also gives you the message: "The following sources have been detected: []"  Additionally, the centres of all 0.0 flux sources are nans.

I also checked if there is a difference between the filtered cube (python array) that you use in the successful run and the cube which is created while running the wavelet filter in the pipeline. Both are the same. Additionally, both cases produce the same mask.

The message about the NaNs in the header is a bit misleading. The NaNs are in the python array that holds the moment maps. More precisely the array consists of only NaNs, which leads to the maximum and minimum values that are estimated to be written to the header to be NaNs as well. Astropy does not permit that.

I suspect the problem is in the parametrisation in the merger module.

**Comment by SoFiA-Admin** [comment]
The output catalogue I get after disabling moment map generation, so SoFiA wouldn’t crash.

**Comment by ngiese** [comment]
If I use the default values from SoFiA_default_input.txt (wavelet filter+threshold), there is no source left after the removal of the negative sources.

**Comment by SoFiA-Admin** [comment]
Default settings won’t work because of the arbitrary flux scale (we need to use an absolute threshold in the threshold finder). The actual parameter file I used is attached:

[Tutorial_Settings_3.txt](https://github.com/SoFiA-Admin/SoFiA/files/30560/Tutorial_Settings_3.txt)

**Comment by ngiese** [comment]
Same result. The mask is not written because after removal of the negative sources there is nothing left. Could you please remove your mask and moment maps in the directory, run again and see if a mask is created? The moment 0 map should be created because in the part of the code where that happens, it is not checked if any voxel was detected.

**Comment by SoFiA-Admin** [comment]
Sorry, my mistake, the threshold in the parameter file is wrong and should have been 0.001, not 0.01. This means that there are actually two different issues here. The fact that the moment map generation crashes is presumably due to the fact that for some reason we are trying to create moment maps even though no sources have been detected. However, the problem is more complex: if I set a threshold of 0.01, no sources are detected, an empty moment-0 map is created, and moment-1 generation crashes. If instead I set a higher threshold of 0.1, again no sources are detected, but no moment maps are created either, and SoFiA finishes without crashing.

So, while in both cases no sources are found, SoFiA behaves differently when it comes to deciding whether moment maps should be generated. Maybe the difference is that in one case pixels above the threshold are found (although not leading to significant sources), while with the higher threshold there are no detections whatsoever?

The second issue is that of the output of SoFiA making no sense when 2D-1D + threshold are used. With the correct threshold of 0.001 I get the following output:

* `sofiatestcube_cat.ascii` and `sofiatestcube_cat.xml`: each with one nonsensical detection.
* `sofiatestcube_mask.fits`: actually looks sensible with the brightest galaxy in the cube detected.
* `sofiatestcube_mom0.fits`: also looks sensible, with the brightest galaxy detected.
* `sofiatestcube_mom1.fits`: again with brightest galaxy, looking fine.
* `sofiatestcube_nrch.fits`: again contains the brightest galaxy and looks fine.

The single source in the catalogue has a peak flux of 0.0009 Jy (with a threshold of 0.001 Jy!), whereas the true peak flux is 0.0217 Jy. That true flux is recovered when I pre-load the filtered cube, but not when running the filter as part of the source finding run.

In addition, SoFiA will erroneously only find the brightest galaxy when I do inline filtering, but correctly recover the two brightest galaxies when pre-loading the filtered cube.

**Comment by ngiese** [comment]
The difference in the behaviours with a threshold of 0.1 and 0.01 is not surprising. For 0.1 no voxel is detected. The pipeline exits in line 257. For a threshold of 0.01 voxels are detected and merged into a source, which is discarded when the negative sources are removed.

**Comment by SoFiA-Admin** [comment]
That’s what I suspected; that should definitely be fixed such that moment maps are only generated when there are sources left after merging.

**Comment by paoloserra** [comment]
The question is whether we want to remove non-positive objects after merging if the reliability is switched off (current SoFiA behaviour), or whether we want to keep all objects regardless of their total flux value. The latter option would avoid the problem you are encountering. It may also be better as it wouldn't assume that the user wants to remove non-positive objects.

**Comment by ngiese** [comment]
I changed it

**Comment by ngiese** [comment]
The moment maps are now only written if sources are detected. 

Keeping the negative sources will not fix the problem. We should investigate why the flux values that we get from the linker are wrong.

**Comment by SoFiA-Admin** [comment]
I have a related question: at the moment we exit in line 257 if no pixels are detected, and in principal we could have a similar check after merging. My question is what happens in the following scenario:

A user loads a mask cube from a previous run of SoFiA and then switches on a different source finder to add sources to that mask (or alternatively disables source finding and only wants parameterisation of the sources in the mask). If that source finder fails to detect any additional sources, would SoFiA then exit or, as one would expect, continue with parameterisation of the existing sources?

**Comment by ngiese** [comment]
It would continue

**Comment by SoFiA-Admin** [comment]
Perfect, thanks.

**Comment by ngiese** [comment]
It is a memory problem

**Comment by ngiese** [comment]
Could you please test the latest version?

**Comment by SoFiA-Admin** [comment]
Works! Excellent job! So, indeed, it is a memory problem, which seems like the only possibility left given that the input to the linker is the same. Do you know why making a copy of the cube is necessary? This would seem like a redundant step. Is there a way we could get around having to make yet another copy?

**Comment by ngiese** [comment]
The problem was not with in the linker, but in the wavelet module. Apparently there is some memory problem with the result from the wavelet filter. The temporary fix copies the cube data into a temporary array, deletes the cube array and then copies the content back into the cube variable again:
  tmpCube = np_Cube.copy()
  del np_Cube
  np_Cube = tmpCube.copy()

**Comment by ngiese** [comment]
There probably is a more elegant fix. I reduced it to one additional line now. I think the copying makes sure that actually the data is copied and not only the memory address of the data. We should try and find the problem in the wavelet module at some point.

**Comment by SoFiA-Admin** [comment]
Thanks a lot! At least we have a functioning workaround for now. The entire 2D-1D filter needs to be overhauled anyway at some point.

**Comment by paoloserra** [comment]
Great job Nadine!

**Comment by RussellJurek** [comment]
Fantastic work Nadine.

Given that there is some sort of corruption in np_Cube that is fixed by
making a copy, it makes sense that writing out the data and re-reading it
in works. It's effectively a very slow and laborious method of making a new
copy of the data.

Is there a chance there's some sort of numpy bug that's contributing to
this?

This bug is definitely another reason to rebuild the 2D-1D module.

**Comment by vdhulst** [comment]
Very nice and fast work indeed! Well done!

**Comment by SoFiA-Admin** [comment]
I will close this issue, as we have a functioning work-around, even though it may not be optimal. We will need to overhaul the 2D-1D finder anyway at some point.
