### ISSUE TITLE
Debug option broken

### ISSUE THREAD

**Issue by ngiese** [SoFiA-Admin/SoFiA#92]
Function calls (e.g. for writing masks) have changed and were not updated in the debug sections of the pipeline.

**Comment by SoFiA-Admin** [comment]
As this issue has been open for over two years now with no progress or intention to fix the debugging functionality, I propose to remove this feature altogether, as it is no longer usable anyway and not relevant to the functioning of SoFiA. Please let me know if you have any objections to this plan.

**Comment by paoloserra** [comment]
I still use it. In fact, I'm not sure what is broken. I'd like to keep this feature.

**Comment by ngiese** [comment]
I remember fixing a few things. I think, I left it open, because I was not done/happy yet. I am in favor of keeping this feature.

**Comment by SoFiA-Admin** [comment]
I just tested the debug option on my installation, and it appears to work fine without crashing the pipeline. It does produce a source catalogue and mask, but one additional debugging step is currently commented out in the code, so doesn’t do anything at the moment. Since there is support for the debugging option, we will leave it in there for now.

As SoFiA currently doesn’t seem to crash any longer with debugging enabled, can we close this issue now? We can always re-open or create a new one if problems reappear.

**Comment by paoloserra** [comment]
We have not had problems with the debugging options for a while. Let's close this for now.
